plugins {
    id 'java'
}

group = 'com.bundleessential'
version = '1.0.21'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.20.4-R0.1-SNAPSHOT'
}

jar {
    archiveBaseName.set('BundledEssential')
    archiveVersion.set('1.0.21')
}

processResources {
    filesMatching('plugin.yml') {
        expand version: project.version
    }
}
